# Generated by Django 2.2.28 on 2023-05-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audioembed", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audioembed",
            name="custom",
            field=models.CharField(
                blank=True, default="", max_length=128, null=True, verbose_name="Custom"
            ),
        ),
        migrations.AlterField(
            model_name="audioembed",
            name="size",
            field=models.CharField(
                blank=True, default="", max_length=64, null=True, verbose_name="Size"
            ),
        ),
    ]
