# Generated by Django 3.2.25 on 2025-08-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audioembed", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audioembed",
            name="oembed_info",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
