# Generated by Django 3.2.25 on 2025-08-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audioembed", "0002_audioembed_oembed_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audioembed",
            name="audioembed_url",
            field=models.URLField(
                help_text="Supports spotify, soundcloud and mixcloud URLs",
                verbose_name="Embed URL",
            ),
        ),
    ]
